name: Docker Image CI
on:
  push:
    branches:
      - master
    tags:
      - 'v*' # This will trigger when semantic-release creates tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check if this is a release
        id: check_release
        run: |
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Available tags:"
          git tag -l --sort=-version:refname | head -10
          echo "Tags pointing to current commit:"
          git tag --points-at HEAD
          echo "Latest tag:"
          git describe --tags --abbrev=0 2>/dev/null || echo "No tags found"

          if git describe --exact-match --tags HEAD 2>/dev/null; then
            echo "is_release=true" >> $GITHUB_OUTPUT
            echo "✅ This is a release commit"
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
            echo "❌ This is not a release commit"
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (release)
        if: steps.check_release.outputs.is_release == 'true'
        run: |
          TAG=$(git describe --tags --exact-match HEAD)
          echo "Building and pushing Docker image with tag: ${TAG}"

          # GitHub Container Registry
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/yerlem-web:${TAG}
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/yerlem-web:latest
          docker push ghcr.io/${{ github.repository_owner }}/yerlem-web:${TAG}
          docker push ghcr.io/${{ github.repository_owner }}/yerlem-web:latest

          echo "Docker images pushed successfully to GHCR"

      - name: Build and push Docker image (development)
        if: steps.check_release.outputs.is_release == 'false'
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "dev")
          echo "Building and pushing development image with tag: ${LATEST_TAG}"

          # GitHub Container Registry
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/yerlem-web:${LATEST_TAG}
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/yerlem-web:dev
          docker push ghcr.io/${{ github.repository_owner }}/yerlem-web:${LATEST_TAG}
          docker push ghcr.io/${{ github.repository_owner }}/yerlem-web:dev

          echo "Development Docker images pushed successfully to GHCR"
